//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        nf_data_sink_regs_defines.h
//
//  Description:
//        This file is automatically generated with header defines for the software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//

##########This text should be copied to the head file #############
   #Registers offset definitions

#define SUME_NF_DATA_SINK_ID_0_OFFSET 0x0
#define SUME_NF_DATA_SINK_ID_0_DEFAULT 0x0000DAD1
#define SUME_NF_DATA_SINK_ID_0_WIDTH 32
#define SUME_NF_DATA_SINK_VERSION_0_OFFSET 0x4
#define SUME_NF_DATA_SINK_VERSION_0_DEFAULT 0x02211526
#define SUME_NF_DATA_SINK_VERSION_0_WIDTH 32
#define SUME_NF_DATA_SINK_RESET_0_OFFSET 0x8
#define SUME_NF_DATA_SINK_RESET_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_RESET_0_WIDTH 32
#define SUME_NF_DATA_SINK_FLIP_0_OFFSET 0xC
#define SUME_NF_DATA_SINK_FLIP_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_FLIP_0_WIDTH 32
#define SUME_NF_DATA_SINK_DEBUG_0_OFFSET 0x10
#define SUME_NF_DATA_SINK_DEBUG_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_DEBUG_0_WIDTH 32
#define SUME_NF_DATA_SINK_ENABLE_0_OFFSET 0x14
#define SUME_NF_DATA_SINK_ENABLE_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_ENABLE_0_WIDTH 32
#define SUME_NF_DATA_SINK_PKTIN_0_OFFSET 0x18
#define SUME_NF_DATA_SINK_PKTIN_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_PKTIN_0_WIDTH 32
#define SUME_NF_DATA_SINK_BYTESINLO_0_OFFSET 0x1c
#define SUME_NF_DATA_SINK_BYTESINLO_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_BYTESINLO_0_WIDTH 32
#define SUME_NF_DATA_SINK_BYTESINHI_0_OFFSET 0x20
#define SUME_NF_DATA_SINK_BYTESINHI_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_BYTESINHI_0_WIDTH 32
#define SUME_NF_DATA_SINK_TIME_0_OFFSET 0x24
#define SUME_NF_DATA_SINK_TIME_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_TIME_0_WIDTH 32
#define SUME_NF_DATA_SINK_AXI_CLK_0_OFFSET 0x28
#define SUME_NF_DATA_SINK_AXI_CLK_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_AXI_CLK_0_WIDTH 32
#define SUME_NF_DATA_SINK_AXIS_CLK_0_OFFSET 0x2c
#define SUME_NF_DATA_SINK_AXIS_CLK_0_DEFAULT 0x0
#define SUME_NF_DATA_SINK_AXIS_CLK_0_WIDTH 32
