//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        output_port_lookup_cpu_regs_defines.v
//
//  Module:
//        output_port_lookup_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


`define  REG_ID_BITS				31:0
`define  REG_ID_WIDTH				32
`define  REG_ID_DEFAULT				32'h0000DA01
`define  REG_ID_ADDR				32'h0

`define  REG_VERSION_BITS				31:0
`define  REG_VERSION_WIDTH				32
`define  REG_VERSION_DEFAULT				32'h1
`define  REG_VERSION_ADDR				32'h4

`define  REG_RESET_BITS				15:0
`define  REG_RESET_WIDTH				16
`define  REG_RESET_DEFAULT				16'h0
`define  REG_RESET_ADDR				32'h8

`define  REG_FLIP_BITS				31:0
`define  REG_FLIP_WIDTH				32
`define  REG_FLIP_DEFAULT				32'h0
`define  REG_FLIP_ADDR				32'hC

`define  REG_DEBUG_BITS				31:0
`define  REG_DEBUG_WIDTH				32
`define  REG_DEBUG_DEFAULT				32'h0
`define  REG_DEBUG_ADDR				32'h10

`define  REG_PKT_SENT_FROM_CPU_CNTR_BITS				31:0
`define  REG_PKT_SENT_FROM_CPU_CNTR_WIDTH				32
`define  REG_PKT_SENT_FROM_CPU_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_FROM_CPU_CNTR_ADDR				32'h14

`define  REG_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_OPTIONS_VER_CNTR_ADDR				32'h18

`define  REG_PKT_SENT_TO_CPU_BAD_TTL_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_BAD_TTL_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_BAD_TTL_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_BAD_TTL_CNTR_ADDR				32'h1C

`define  REG_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_DEST_IP_HIT_CNTR_ADDR				32'h20

`define  REG_PKT_FORWARDED_CNTR_BITS				31:0
`define  REG_PKT_FORWARDED_CNTR_WIDTH				32
`define  REG_PKT_FORWARDED_CNTR_DEFAULT				32'h0
`define  REG_PKT_FORWARDED_CNTR_ADDR				32'h24

`define  REG_PKT_DROPPED_CHECKSUM_CNTR_BITS				31:0
`define  REG_PKT_DROPPED_CHECKSUM_CNTR_WIDTH				32
`define  REG_PKT_DROPPED_CHECKSUM_CNTR_DEFAULT				32'h0
`define  REG_PKT_DROPPED_CHECKSUM_CNTR_ADDR				32'h28

`define  REG_PKT_SENT_TO_CPU_NON_IP_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_NON_IP_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_NON_IP_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_NON_IP_CNTR_ADDR				32'h2C

`define  REG_PKT_SENT_TO_CPU_ARP_MISS_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_ARP_MISS_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_ARP_MISS_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_ARP_MISS_CNTR_ADDR				32'h30

`define  REG_PKT_SENT_TO_CPU_LPM_MISS_CNTR_BITS				31:0
`define  REG_PKT_SENT_TO_CPU_LPM_MISS_CNTR_WIDTH				32
`define  REG_PKT_SENT_TO_CPU_LPM_MISS_CNTR_DEFAULT				32'h0
`define  REG_PKT_SENT_TO_CPU_LPM_MISS_CNTR_ADDR				32'h34

`define  REG_PKT_DROPPED_WRONG_DST_MAC_CNTR_BITS				31:0
`define  REG_PKT_DROPPED_WRONG_DST_MAC_CNTR_WIDTH				32
`define  REG_PKT_DROPPED_WRONG_DST_MAC_CNTR_DEFAULT				32'h0
`define  REG_PKT_DROPPED_WRONG_DST_MAC_CNTR_ADDR				32'h38

`define  REG_MAC_0_HI_BITS				31:0
`define  REG_MAC_0_HI_WIDTH				32
`define  REG_MAC_0_HI_DEFAULT				32'h0
`define  REG_MAC_0_HI_ADDR				32'h3C

`define  REG_MAC_0_LOW_BITS				31:0
`define  REG_MAC_0_LOW_WIDTH				32
`define  REG_MAC_0_LOW_DEFAULT				32'h0
`define  REG_MAC_0_LOW_ADDR				32'h40

`define  REG_MAC_1_HI_BITS				31:0
`define  REG_MAC_1_HI_WIDTH				32
`define  REG_MAC_1_HI_DEFAULT				32'h0
`define  REG_MAC_1_HI_ADDR				32'h44

`define  REG_MAC_1_LOW_BITS				31:0
`define  REG_MAC_1_LOW_WIDTH				32
`define  REG_MAC_1_LOW_DEFAULT				32'h0
`define  REG_MAC_1_LOW_ADDR				32'h48

`define  REG_MAC_2_HI_BITS				31:0
`define  REG_MAC_2_HI_WIDTH				32
`define  REG_MAC_2_HI_DEFAULT				32'h0
`define  REG_MAC_2_HI_ADDR				32'h4C

`define  REG_MAC_2_LOW_BITS				31:0
`define  REG_MAC_2_LOW_WIDTH				32
`define  REG_MAC_2_LOW_DEFAULT				32'h0
`define  REG_MAC_2_LOW_ADDR				32'h50

`define  REG_MAC_3_HI_BITS				31:0
`define  REG_MAC_3_HI_WIDTH				32
`define  REG_MAC_3_HI_DEFAULT				32'h0
`define  REG_MAC_3_HI_ADDR				32'h54

`define  REG_MAC_3_LOW_BITS				31:0
`define  REG_MAC_3_LOW_WIDTH				32
`define  REG_MAC_3_LOW_DEFAULT				32'h0
`define  REG_MAC_3_LOW_ADDR				32'h58

`define  REG_INDIRECTADDRESS_BITS				31:0
`define  REG_INDIRECTADDRESS_WIDTH				32
`define  REG_INDIRECTADDRESS_DEFAULT				32'h0
`define  REG_INDIRECTADDRESS_ADDR				32'h5C

`define  REG_INDIRECTWRDATA_A_HI_BITS				31:0
`define  REG_INDIRECTWRDATA_A_HI_WIDTH				32
`define  REG_INDIRECTWRDATA_A_HI_DEFAULT				32'h0
`define  REG_INDIRECTWRDATA_A_HI_ADDR				32'h60

`define  REG_INDIRECTWRDATA_A_LOW_BITS				31:0
`define  REG_INDIRECTWRDATA_A_LOW_WIDTH				32
`define  REG_INDIRECTWRDATA_A_LOW_DEFAULT				32'h0
`define  REG_INDIRECTWRDATA_A_LOW_ADDR				32'h64

`define  REG_INDIRECTWRDATA_B_HI_BITS				31:0
`define  REG_INDIRECTWRDATA_B_HI_WIDTH				32
`define  REG_INDIRECTWRDATA_B_HI_DEFAULT				32'h0
`define  REG_INDIRECTWRDATA_B_HI_ADDR				32'h68

`define  REG_INDIRECTWRDATA_B_LOW_BITS				31:0
`define  REG_INDIRECTWRDATA_B_LOW_WIDTH				32
`define  REG_INDIRECTWRDATA_B_LOW_DEFAULT				32'h0
`define  REG_INDIRECTWRDATA_B_LOW_ADDR				32'h6C

`define  REG_INDIRECTREPLY_A_HI_BITS				31:0
`define  REG_INDIRECTREPLY_A_HI_WIDTH				32
`define  REG_INDIRECTREPLY_A_HI_DEFAULT				32'h0
`define  REG_INDIRECTREPLY_A_HI_ADDR				32'h70

`define  REG_INDIRECTREPLY_A_LOW_BITS				31:0
`define  REG_INDIRECTREPLY_A_LOW_WIDTH				32
`define  REG_INDIRECTREPLY_A_LOW_DEFAULT				32'h0
`define  REG_INDIRECTREPLY_A_LOW_ADDR				32'h74

`define  REG_INDIRECTREPLY_B_HI_BITS				31:0
`define  REG_INDIRECTREPLY_B_HI_WIDTH				32
`define  REG_INDIRECTREPLY_B_HI_DEFAULT				32'h0
`define  REG_INDIRECTREPLY_B_HI_ADDR				32'h78

`define  REG_INDIRECTREPLY_B_LOW_BITS				31:0
`define  REG_INDIRECTREPLY_B_LOW_WIDTH				32
`define  REG_INDIRECTREPLY_B_LOW_DEFAULT				32'h0
`define  REG_INDIRECTREPLY_B_LOW_ADDR				32'h7C

`define  REG_INDIRECTCOMMAND_BITS				31:0
`define  REG_INDIRECTCOMMAND_WIDTH				32
`define  REG_INDIRECTCOMMAND_DEFAULT				32'h0
`define  REG_INDIRECTCOMMAND_ADDR				32'h80

`define  REG_INDIRECTCONFIG_BITS				31:0
`define  REG_INDIRECTCONFIG_WIDTH				32
`define  REG_INDIRECTCONFIG_DEFAULT				32'h0
`define  REG_INDIRECTCONFIG_ADDR				32'h84

`define  MEM_IP_LPM_TCAM_DATA_BITS				31:0
`define  MEM_IP_LPM_TCAM_ADDR_BITS				4:0
`define  MEM_IP_LPM_TCAM_WIDTH				32
`define  MEM_IP_LPM_TCAM_DEPTH				32
`define  MEM_IP_LPM_TCAM_ADDR				32'h00000000

`define  MEM_IP_ARP_CAM_DATA_BITS				31:0
`define  MEM_IP_ARP_CAM_ADDR_BITS				4:0
`define  MEM_IP_ARP_CAM_WIDTH				32
`define  MEM_IP_ARP_CAM_DEPTH				32
`define  MEM_IP_ARP_CAM_ADDR				32'h10000000

`define  MEM_DEST_IP_CAM_DATA_BITS				31:0
`define  MEM_DEST_IP_CAM_ADDR_BITS				4:0
`define  MEM_DEST_IP_CAM_WIDTH				32
`define  MEM_DEST_IP_CAM_DEPTH				32
`define  MEM_DEST_IP_CAM_ADDR				32'h20000000
