//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        output_port_lookup_regs_defines.h
//
//  Description:
//        This file is automatically generated with header defines for the software
//
// This software was developed by
// Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//

##########This text should be copied to the head file #############
   #Registers offset definitions

#define NFPLUS_OUTPUT_PORT_LOOKUP_ID_0_OFFSET 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_ID_0_DEFAULT 0x0001DA02
#define NFPLUS_OUTPUT_PORT_LOOKUP_ID_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_VERSION_0_OFFSET 0x4
#define NFPLUS_OUTPUT_PORT_LOOKUP_VERSION_0_DEFAULT 0x1
#define NFPLUS_OUTPUT_PORT_LOOKUP_VERSION_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_RESET_0_OFFSET 0x8
#define NFPLUS_OUTPUT_PORT_LOOKUP_RESET_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_RESET_0_WIDTH 16
#define NFPLUS_OUTPUT_PORT_LOOKUP_FLIP_0_OFFSET 0xC
#define NFPLUS_OUTPUT_PORT_LOOKUP_FLIP_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_FLIP_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_DEBUG_0_OFFSET 0x10
#define NFPLUS_OUTPUT_PORT_LOOKUP_DEBUG_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_DEBUG_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTIN_0_OFFSET 0x14
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTIN_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTIN_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTOUT_0_OFFSET 0x18
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTOUT_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_PKTOUT_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTHIT_0_OFFSET 0x1C
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTHIT_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTHIT_0_WIDTH 32
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTMISS_0_OFFSET 0x20
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTMISS_0_DEFAULT 0x0
#define NFPLUS_OUTPUT_PORT_LOOKUP_LUTMISS_0_WIDTH 32
